package MultiThreading_Concepts;

public class Thread_Priorities_Explanation {
	
	/*Thread Priorities:
	  Every thread in Java has some priority. It may be default priority generated by
	  jvm or customized provided by programmer. The valid range of thread priorities are
	  1 - 10  , 1 is min  prority, 5 - norm priority,10- max priority. Thread class defines
	  the following constants to represent some standard priorities
	  thread. min pririty -1 
	 thread. norm pririty -5
	 thread. max pririty -10
	 
	 Thread scheduler will use priorities while allocating processor. The thread which is
	 having highest priority will get the chance first 
	 
	 If two threads having same priority then we cant expect exact execution order. It depends 
	 on thread scheduler.
	 
	 Thread class defines the following methods to get and set priority of a thread.
	  public final int getpriority
	  public final void setpriority(int p)
	  allowed  values range 1 to 10 otherwise runtime exception - Illegal argument exception
	  
	  t.setpriority(7)
	  t.setpriority(17)
	  
	  Default priority:
	  The default priority only for the main thread is 5 . But for all remaining threads
	  the default priority will be inherited from parent to child(i.e) whatever priority 
	  parent thread has the same priority will be there for the child thread 31:26
	 
	 
	 
	*/

}
